### ISSUE TITLE
如何获取论文

### ISSUE THREAD

**Issue by chengchegn** [sx1616039/DRL4DJSP#1]
你好！请问怎么样下载代码对应的论文？谷歌学术以及其它数据库里都没有找到

**Comment by sx1616039** [comment]
这篇论文正在审稿中，二审快结束了，等上线了我会通知你的。

**Comment by chengchegn** [comment]
> 这篇论文正在审稿中，二审快结束了，等上线了我会通知你的。

好的，非常感谢！

**Comment by sx1616039** [comment]
A deep reinforcement learning model for dynamic job-shop scheduling problem with uncertain processing time - ScienceDirect




Small&nbsp;??
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sx1616039/DRL4DJSP"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月28日(星期二) 下午4:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sx1616039/DRL4DJSP] 如何获取论文 (Issue #1)





 
你好！请问怎么样下载代码对应的论文？谷歌学术以及其它数据库里都没有找到
